# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiDLG.ui'
#
# Created: Sat Nov 07 21:43:02 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(615, 272)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/bccscbar/res/img/bccscbar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.radUseCurrent = QtGui.QRadioButton(Dialog)
        self.radUseCurrent.setMinimumSize(QtCore.QSize(160, 45))
        self.radUseCurrent.setBaseSize(QtCore.QSize(160, 45))
        self.radUseCurrent.setObjectName(_fromUtf8("radUseCurrent"))
        self.gridLayout_3.addWidget(self.radUseCurrent, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.btnEntry = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEntry.sizePolicy().hasHeightForWidth())
        self.btnEntry.setSizePolicy(sizePolicy)
        self.btnEntry.setMinimumSize(QtCore.QSize(400, 30))
        self.btnEntry.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnEntry.setBaseSize(QtCore.QSize(400, 30))
        self.btnEntry.setObjectName(_fromUtf8("btnEntry"))
        self.gridLayout_3.addWidget(self.btnEntry, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 4)
        self.groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(161, 80))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radAspect1 = QtGui.QRadioButton(self.groupBox)
        self.radAspect1.setGeometry(QtCore.QRect(12, 22, 131, 18))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radAspect1.sizePolicy().hasHeightForWidth())
        self.radAspect1.setSizePolicy(sizePolicy)
        self.radAspect1.setObjectName(_fromUtf8("radAspect1"))
        self.radAspect2 = QtGui.QRadioButton(self.groupBox)
        self.radAspect2.setGeometry(QtCore.QRect(12, 46, 131, 18))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radAspect2.sizePolicy().hasHeightForWidth())
        self.radAspect2.setSizePolicy(sizePolicy)
        self.radAspect2.setObjectName(_fromUtf8("radAspect2"))
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtTitle = QtGui.QLineEdit(Dialog)
        self.txtTitle.setObjectName(_fromUtf8("txtTitle"))
        self.gridLayout.addWidget(self.txtTitle, 0, 1, 1, 3)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtUnits = QtGui.QLineEdit(Dialog)
        self.txtUnits.setObjectName(_fromUtf8("txtUnits"))
        self.gridLayout.addWidget(self.txtUnits, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(37, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 1, 1, 3)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 95))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(11, 25, 41, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.txtW = QtGui.QLineEdit(self.groupBox_3)
        self.txtW.setGeometry(QtCore.QRect(70, 25, 81, 20))
        self.txtW.setObjectName(_fromUtf8("txtW"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(11, 60, 41, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.txtH = QtGui.QLineEdit(self.groupBox_3)
        self.txtH.setGeometry(QtCore.QRect(70, 60, 81, 20))
        self.txtH.setObjectName(_fromUtf8("txtH"))
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(146, 115))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radTick1 = QtGui.QRadioButton(self.groupBox_2)
        self.radTick1.setGeometry(QtCore.QRect(11, 21, 121, 18))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radTick1.sizePolicy().hasHeightForWidth())
        self.radTick1.setSizePolicy(sizePolicy)
        self.radTick1.setChecked(True)
        self.radTick1.setObjectName(_fromUtf8("radTick1"))
        self.RadTick2 = QtGui.QRadioButton(self.groupBox_2)
        self.RadTick2.setGeometry(QtCore.QRect(11, 55, 121, 18))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RadTick2.sizePolicy().hasHeightForWidth())
        self.RadTick2.setSizePolicy(sizePolicy)
        self.RadTick2.setObjectName(_fromUtf8("RadTick2"))
        self.txtNbTicks = QtGui.QLineEdit(self.groupBox_2)
        self.txtNbTicks.setGeometry(QtCore.QRect(50, 80, 55, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtNbTicks.sizePolicy().hasHeightForWidth())
        self.txtNbTicks.setSizePolicy(sizePolicy)
        self.txtNbTicks.setMinimumSize(QtCore.QSize(55, 0))
        self.txtNbTicks.setMaximumSize(QtCore.QSize(55, 16777215))
        self.txtNbTicks.setObjectName(_fromUtf8("txtNbTicks"))
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 3)
        self.txtDecimal = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDecimal.sizePolicy().hasHeightForWidth())
        self.txtDecimal.setSizePolicy(sizePolicy)
        self.txtDecimal.setMinimumSize(QtCore.QSize(30, 0))
        self.txtDecimal.setMaximumSize(QtCore.QSize(30, 16777215))
        self.txtDecimal.setObjectName(_fromUtf8("txtDecimal"))
        self.gridLayout_2.addWidget(self.txtDecimal, 0, 3, 1, 1)
        self.ckEnforce = QtGui.QCheckBox(Dialog)
        self.ckEnforce.setObjectName(_fromUtf8("ckEnforce"))
        self.gridLayout_2.addWidget(self.ckEnforce, 0, 4, 1, 1)
        self.ckExtrema = QtGui.QCheckBox(Dialog)
        self.ckExtrema.setObjectName(_fromUtf8("ckExtrema"))
        self.gridLayout_2.addWidget(self.ckExtrema, 1, 0, 1, 5)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 2)
        self.txtMinimum = QtGui.QLineEdit(Dialog)
        self.txtMinimum.setObjectName(_fromUtf8("txtMinimum"))
        self.gridLayout_2.addWidget(self.txtMinimum, 2, 2, 1, 3)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 3)
        self.cbFSize = QtGui.QComboBox(Dialog)
        self.cbFSize.setObjectName(_fromUtf8("cbFSize"))
        self.gridLayout_2.addWidget(self.cbFSize, 3, 3, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btnOut = QtGui.QPushButton(Dialog)
        self.btnOut.setObjectName(_fromUtf8("btnOut"))
        self.verticalLayout.addWidget(self.btnOut)
        self.btnCreate = QtGui.QPushButton(Dialog)
        self.btnCreate.setObjectName(_fromUtf8("btnCreate"))
        self.verticalLayout.addWidget(self.btnCreate)
        self.btnInfo = QtGui.QPushButton(Dialog)
        self.btnInfo.setObjectName(_fromUtf8("btnInfo"))
        self.verticalLayout.addWidget(self.btnInfo)
        self.btnExit = QtGui.QPushButton(Dialog)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.verticalLayout.addWidget(self.btnExit)
        self.gridLayout_4.addLayout(self.verticalLayout, 2, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.radAspect1, self.radAspect2)
        Dialog.setTabOrder(self.radAspect2, self.txtW)
        Dialog.setTabOrder(self.txtW, self.txtH)
        Dialog.setTabOrder(self.txtH, self.txtTitle)
        Dialog.setTabOrder(self.txtTitle, self.txtUnits)
        Dialog.setTabOrder(self.txtUnits, self.radTick1)
        Dialog.setTabOrder(self.radTick1, self.RadTick2)
        Dialog.setTabOrder(self.RadTick2, self.txtNbTicks)
        Dialog.setTabOrder(self.txtNbTicks, self.ckExtrema)
        Dialog.setTabOrder(self.ckExtrema, self.txtMinimum)
        Dialog.setTabOrder(self.txtMinimum, self.txtDecimal)
        Dialog.setTabOrder(self.txtDecimal, self.ckEnforce)
        Dialog.setTabOrder(self.ckEnforce, self.btnCreate)
        Dialog.setTabOrder(self.btnCreate, self.btnInfo)
        Dialog.setTabOrder(self.btnInfo, self.btnExit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Colour Scale Bar for one-band rasters", None))
        self.radUseCurrent.setText(_translate("Dialog", "Use current raster", None))
        self.btnEntry.setText(_translate("Dialog", "Click to select a colour table (*.txt) or a QGIS properties file (*.qml)", None))
        self.groupBox.setTitle(_translate("Dialog", "Aspect", None))
        self.radAspect1.setToolTip(_translate("Dialog", "Create a vertical colour scale bar", None))
        self.radAspect1.setText(_translate("Dialog", "Vertical", None))
        self.radAspect2.setToolTip(_translate("Dialog", "Create a horizontal colour scale bar", None))
        self.radAspect2.setText(_translate("Dialog", "Horizontal", None))
        self.label.setText(_translate("Dialog", "Title", None))
        self.label_2.setText(_translate("Dialog", "Units", None))
        self.label_7.setText(_translate("Dialog", "Use \\n to introduce a linefeed in the title string", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Box size (pixels)", None))
        self.label_3.setText(_translate("Dialog", "Width", None))
        self.label_4.setText(_translate("Dialog", "Height", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Tick spacing", None))
        self.radTick1.setText(_translate("Dialog", "Automatic", None))
        self.RadTick2.setText(_translate("Dialog", "Number of ticks", None))
        self.label_5.setText(_translate("Dialog", "Max decimal places", None))
        self.txtDecimal.setText(_translate("Dialog", "4", None))
        self.ckEnforce.setText(_translate("Dialog", "Enforce", None))
        self.ckExtrema.setText(_translate("Dialog", "Annotate extrema", None))
        self.label_6.setText(_translate("Dialog", "Minimum", None))
        self.label_8.setText(_translate("Dialog", "Font size", None))
        self.btnOut.setText(_translate("Dialog", "Sel out dir...", None))
        self.btnCreate.setText(_translate("Dialog", "Create", None))
        self.btnInfo.setText(_translate("Dialog", "Info", None))
        self.btnExit.setText(_translate("Dialog", "Exit", None))

import resources
